#!/bin/bash
set -ex

COMMAND=$SHELL
if [[ $# -eq 1 ]]; then
    COMMAND="$1"
fi

ROOT=$(dirname $(realpath $0))
eval $(${ROOT}/id)

CONTAINER_NAME="devenv-$DOCKER_REPO-$DOCKER_TAG_ID"
CONTAINER_NAME=${CONTAINER_NAME/\//-}

docker run --rm --user "$(id -g):$(id -u)" -it \
    -v "${HOME}:/home/docker" \
    -e "DISPLAY=$DISPLAY" \
    -e "TERM=$TERM" \
    --network=host \
    --name=$CONTAINER_NAME \
    --workdir=/home/docker/$(realpath --relative-to=$HOME $(pwd)) \
$DOCKER_IMAGE $COMMAND
